
option(MAUENG_ENABLE_DEBUG_RENDERING "Enable debug rendering" ON)
option(MAUENG_LOG_TO_FILE "Log to file" OFF)
option(MAUENG_ENABLE_ASSERTS "Enable asserts" ON)

option(MAUENG_ENABLE_PROFILER "Enable profiling" ON)
option(MAUENG_USE_OPTICK "Use Optick instead of custom profiler" OFF)

# set(MAUENG_ENABLE_DEBUG_RENDERING ${MAUENG_ENABLE_DEBUG_RENDERING} CACHE BOOL "Enable debug rendering")
# set(MAUENG_LOG_TO_FILE ${MAUENG_LOG_TO_FILE} CACHE BOOL "Log to file")
# set(MAUENG_ENABLE_ASSERTS ${MAUENG_ENABLE_ASSERTS} CACHE BOOL "Enable asserts")

# set(MAUENG_ENABLE_PROFILER ${MAUENG_ENABLE_PROFILER} CACHE BOOL "Enable profiling")
# set(MAUENG_USE_OPTICK ${MAUENG_USE_OPTICK} CACHE BOOL "Use Optick instead of custom profiler")

message(STATUS "MAUENG_ENABLE_DEBUG_RENDERING: ${MAUENG_ENABLE_DEBUG_RENDERING}")
message(STATUS "MAUENG_LOG_TO_FILE: ${MAUENG_LOG_TO_FILE}")
message(STATUS "MAUENG_ENABLE_ASSERTS: ${MAUENG_ENABLE_ASSERTS}")

message(STATUS "MAUENG_ENABLE_PROFILER: ${MAUENG_ENABLE_PROFILER}")
message(STATUS "MAUENG_USE_OPTICK: ${MAUENG_USE_OPTICK}")